baseUri:
/restaurants/v1:
  post:
    description: Create a restaurant entry
    body:
      application/json:
        example: |
          {
            "name": "Byron Burger",
            "description": "High end burger restaurants",
            "type": ["Burger"]
          }
    responses:
      200:
        description: Success
        body:
          application/json:
            example: |
              {
                "id": "UUID",
                "name": "Byron Burger",
                "description": "High end burger restaurant",
                "type": ["Burger"]
              }
      400:
        description: Bad request, restaurant name not specified
        body:
          application/json:
            example: |
              { "message": "Mandatory field restaurant name not specified" }
  get:
    description: Get restaurants stored in CSV
    queryParameters:
      id:
        type: UUID
        description: Restaurant id (UUID)
        required: true
      name:
        type: string
        description: Name of restaurant
        example: "Wagamama"
        required: true
      responses:
        200:
          body:
            application/json:
        500:
                description: Application error.
                body:
                  application/json:
                    example: |
                      { "message": "reason for failure" }
/restaurants/v1/{restaurantId}:
  get:
    description: Get restaurants by UUID
    queryParameters:
      id:
        description: Restaurant's UUID
        type: UUID
      responses:
        200:
          body:
            application/json:
        404:
          description: Could not find restaurant Id
          body:
            application/json:
              example: |
                { "message": "Could not find restaurant" }




