baseUri: /
/restaurants/v1:
  post:
    description: Create a restaurant entry
    body:
      application/json:
        example: |
          {
            "name": "Byron Burger",
            "description": "High end burger restaurants",
            "type": ["Burger"]
          }
    responses:
      200:
        description: Success
        body:
          application/json:
            example: |
              {
                "id": "xxx",
                "name": "Byron Burger",
                "description": "High end burger restaurant",
                "type": ["Burger"]
              }
      400:
        description: Bad request, restaurant name not specified
        body:
          application/json:
            example: |
              { "message": "Mandatory field restaurant name not specified" }
  get:
    queryParameters:
      name:
        displayName: Restaurant name
        type: string
        description: Name of restaurant
        example: "Wagamama"
        required: true
      responses:
        200:
          body:
            application/json:
              example: |
                { "restaurants": [
                  {
                    "restaurantId": "xxx",
                    "restaurantName": "Wagamama",
                    "description": "Overall asian food",
                    "address": "1, Clink Street",
                    "telephone": "020-7403-3659",
                    "priceRange": "£15-£20",
                    "openingHours": {
                      "Monday": "9:00 - 17:00",
                      "Tuesday": "9:00 - 17:00",
                      "Wednesday": "9:00 - 17:00",
                      "Thursday": "9:00 - 17:00",
                      "Friday": "9:00 - 17:00",
                      "Saturday": "9:00 - 17:00",
                      "Sunday": "Closed"
                    },
                    "restaurantType": ["Thai", "Japanese", "Chinese"],
                    "tags": ["wagamama", "ramen", "gyoza"]
                  }]
                }
        500:
                description: Application error.
                body:
                  application/json:
                    example: |
                      { "message": "reason for failure" }
/restaurants/v1/{restaurantId}:
  get:
    description: Get restaurants by UUID
    queryParameters:
      restaurantId:
        description: Restaurant's UUID
        type: string
      responses:
        200:
          body:
            application/json:
              example: |
                { "restaurants": [
                  {
                    "restaurantId": "xxx",
                    "restaurantName": "Wagamama",
                    "description": "Overall asian food",
                    "address": "1, Clink Street",
                    "telephone": "020-7403-3659",
                    "priceRange": "£15-£20",
                    "openingHours": {
                      "Monday": "9:00 - 17:00",
                      "Tuesday": "9:00 - 17:00",
                      "Wednesday": "9:00 - 17:00",
                      "Thursday": "9:00 - 17:00",
                      "Friday": "9:00 - 17:00",
                      "Saturday": "9:00 - 17:00",
                      "Sunday": "Closed"
                    },
                    "restaurantType": ["Thai", "Japanese", "Chinese"],
                    "tags": ["wagamama", "ramen", "gyoza"]
                  }]
                }
        404:
          description: Could not find restaurant Id
          body:
            application/json:
              example: |
                { "message": "Could not find restaurant" }




